export interface Photo {
  src: string;
  alt: string;
  caption: string;
  width: number;
  height: number;
  blurDataURL: string;
}

export const photos: Photo[] = [
  {
    src: "/photos/three-peaks.jpg",
    alt: "The third peak",
    caption: "Mt. Olomana, Oahu",
    width: 2560,
    height: 3840,
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2P/2wBDARESEhgVGC8aGi9jQjhCY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2P/wAARCAAUAA0DASIAAhEBAxEB/8QAGQAAAgMBAAAAAAAAAAAAAAAAAAIDBAUG/8QAIRAAAQQBAwUAAAAAAAAAAAAAAQACAwQREhQhIiNhcoH/xAAWAQEBAQAAAAAAAAAAAAAAAAAAAQP/xAAXEQEAAwAAAAAAAAAAAAAAAAAAAQIR/9oADAMBAAIRAxEAPwDWZbqAc2Ys+ySSxDq4njI8OXDS2OgOaMDKTcl3ICz0RPPbx9VXUQAhCVWX/9k=",
  },
  {
    src: "/photos/charlift.jpg",
    alt: "Chairlift",
    caption: "Breckenridge, Colorado",
    width: 3089,
    height: 2048,
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2P/2wBDARESEhgVGC8aGi9jQjhCY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2P/wAARCAANABQDASIAAhEBAxEB/8QAGAAAAwEBAAAAAAAAAAAAAAAAAAMGBAX/xAAiEAACAgIBBQADAAAAAAAAAAABAgMEABEhBQYiMYESUcH/xAAVAQEBAAAAAAAAAAAAAAAAAAAAAv/EABcRAQEBAQAAAAAAAAAAAAAAAAABESH/2gAMAwEAAhEDEQA/AKOtfreCSSKkjnhCwOvo4zld3XFSCKFHT2WY++f1rHdI6PXRI7Eu5ZTzv0o+Zk7siWtXrtCAn4hhrXv7k3cVJ1GkyuzEk73o+QX+4Y6xZiqiJHqxTMUDF23vknDA/9k=",
  },
  {
    src: "/photos/lighthouse.jpg",
    alt: "Lighthouse",
    caption: "Makapuu Point, Oahu",
    width: 2560,
    height: 3840,
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2P/2wBDARESEhgVGC8aGi9jQjhCY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2P/wAARCAAUAA0DASIAAhEBAxEB/8QAGAAAAwEBAAAAAAAAAAAAAAAAAAMEAQX/xAAhEAACAQMEAwEAAAAAAAAAAAABAgADBBEFEhMxQVFxYf/EABUBAQEAAAAAAAAAAAAAAAAAAAQF/8QAGxEAAgEFAAAAAAAAAAAAAAAAAAEEAgMhMkH/2gAMAwEAAhEDEQA/AFKwqKHp1AynogzSr+xOVpd2ttdvz0t6OpDr1tPhhKjqlMHDKSPBDYiaZC6S7kFrTJMiA2nIckgY+/YmhtIIKLgfkIQaKh//2Q==",
  },
  {
    src: "/photos/lone-boat.jpg",
    alt: "A lone boat on the water",
    caption: "Oahu",
    width: 2560,
    height: 3840,
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2P/2wBDARESEhgVGC8aGi9jQjhCY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2P/wAARCAAUAA0DASIAAhEBAxEB/8QAGAAAAwEBAAAAAAAAAAAAAAAAAAMFAgT/xAAfEAABAwMFAAAAAAAAAAAAAAAAAQIEBVGRERMxQWH/xAAVAQEBAAAAAAAAAAAAAAAAAAACBP/EABcRAQADAAAAAAAAAAAAAAAAAAABESH/2gAMAwEAAhEDEQA/AO5Y3gtY6a8EdaxJXtuBa1eTduCvUdQkq91zG464AE3/2Q==",
  },
  {
    src: "/photos/marlinszn.jpg",
    alt: "Marlin",
    caption: "Pacific Ocean, Oahu",
    width: 3840,
    height: 2161,
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2P/2wBDARESEhgVGC8aGi9jQjhCY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2P/wAARCAALABQDASIAAhEBAxEB/8QAFwABAQEBAAAAAAAAAAAAAAAABgACBP/EACIQAAICAQMEAwAAAAAAAAAAAAECAxEABBJBBiEiMRMjUf/EABYBAQEBAAAAAAAAAAAAAAAAAAMBBP/EABsRAAIDAAMAAAAAAAAAAAAAAAABAgMREjFx/9oADAMBAAIRAxEAPwAvNEPlMmkVxEK2ub7n9vMaqmkbxqVDtfaPEkeziqD6+mzsAFISO184VjdpGZ2Yljbk+u+NVNyfhbalCKe9nNRHGWJ9FGk0O6RbIIA44GWLzM+H/9k=",
  },
  {
    src: "/photos/moon.jpg",
    alt: "The moon",
    caption: "Pompano Beach, Florida",
    width: 2048,
    height: 1364,
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2P/2wBDARESEhgVGC8aGi9jQjhCY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2P/wAARCAANABQDASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAAMGBP/EACYQAAEDAwMCBwAAAAAAAAAAAAECAwQABRESITETMiJRYXGBkcH/xAAWAQEBAQAAAAAAAAAAAAAAAAACAAP/xAAYEQADAQEAAAAAAAAAAAAAAAAAARECEv/aAAwDAQACEQMRAD8AbcLqhVk6raFgrUlGkbFWRxms9zsaI0WO5LWhL5UO3gbdu/PvSGzIvkByc68lpMYdZthCPACn59Oar7vCTOgR5WrQ5HUmQkYyCccH7rZ6ClCQZtIcbDgiqIUTgkc4OPyir/QkhJ0gZAOPKirsUP/Z",
  },
  {
    src: "/photos/old-rag.jpg",
    alt: "Old Rag",
    caption: "Shenandoah, Virginia",
    width: 3840,
    height: 2560,
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2P/2wBDARESEhgVGC8aGi9jQjhCY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2P/wAARCAANABQDASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAAMGBP/EACEQAAEFAAAHAQAAAAAAAAAAAAEAAgMEEQUSISMxcYGC/8QAFgEBAQEAAAAAAAAAAAAAAAAAAQAC/8QAFxEBAQEBAAAAAAAAAAAAAAAAABIBE//aAAwDAQACEQMRAD8A2NtVM7g5P0ClTXKTPEjvikDZkLep1IklcRmlFM81LNxSm2QgPefSFJ7qE1qjH//Z",
  },
  {
    src: "/photos/palm.jpg",
    alt: "Palm tree",
    caption: "Pompano Beach, Florida",
    width: 2048,
    height: 1364,
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2P/2wBDARESEhgVGC8aGi9jQjhCY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2P/wAARCAANABQDASIAAhEBAxEB/8QAFwABAQEBAAAAAAAAAAAAAAAAAAIBBf/EACUQAAEEAQMCBwAAAAAAAAAAAAECAwQRAAUSQRMhIjEyUrHB4f/EABYBAQEBAAAAAAAAAAAAAAAAAAQAA//EABkRAQEAAwEAAAAAAAAAAAAAAAEAAhExcf/aAAwDAQACEQMRAD8AStSd68aVVqaBQaB3KSR3Cvo5WmzpTTCWOlstFAX5DlRydQabkREvJBQ7YAN2PVXcc50FndHO6ilKR4QKHOHwF4yDA3ulmLFLY6kh1Kva0DQ/cZscuhlITJeSBwkgD4xmwU+3/9k=",
  },
  {
    src: "/photos/pompano.jpg",
    alt: "Pompano Beach",
    caption: "Pompano Beach, Florida",
    width: 2048,
    height: 1364,
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2P/2wBDARESEhgVGC8aGi9jQjhCY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2P/wAARCAANABQDASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAAUGB//EACUQAAIBAgUEAwEAAAAAAAAAAAECAwARBAUGEiETMYGRFEFR4f/EABYBAQEBAAAAAAAAAAAAAAAAAAIAAf/EABcRAAMBAAAAAAAAAAAAAAAAAAABAhL/2gAMAwEAAhEDEQA/AKU4EHFJN9ANfyP5S/ZBgM2V5MQsfyLrEH7MeOL1I5Zq7M4uoJ5TOiqWsxsfdPdS4WLGGCaTduSFnB3G/FiOfNTphUFCxIY3Rb/vVtRWfLrHOAoCyxWAsLxKT7Peinpm5P/Z",
  },
  {
    src: "/photos/steeple.jpg",
    alt: "Church steeple",
    caption: "Charleston, South Carolina",
    width: 1960,
    height: 2941,
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2P/2wBDARESEhgVGC8aGi9jQjhCY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2P/wAARCAAUAA0DASIAAhEBAxEB/8QAGAAAAwEBAAAAAAAAAAAAAAAAAAQGAQX/xAAjEAADAAIABAcAAAAAAAAAAAABAgMABBESIVEFBhMxMkFS/8QAFQEBAQAAAAAAAAAAAAAAAAAAAQD/xAAWEQEBAQAAAAAAAAAAAAAAAAAAARL/2gAMAwEAAhEDEQA/ALZyvcZgZf0MXpsSac6Toro9AgKniOucvxDzBp6F/RYGjj5cp9sMQ6qEtubEGZY1aYJBPKeHXviDUd2LMxJP2ThhjFX/2Q==",
  },
  {
    src: "/photos/beached.jpg",
    alt: "Beached boat in costa rica",
    caption: "Esterillos Oeste, Costa Rica",
    width: 2560,
    height: 3840,
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2P/2wBDARESEhgVGC8aGi9jQjhCY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2P/wAARCAAUAA0DASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAAUGAf/EACIQAAICAwABBAMAAAAAAAAAAAECAwQAESEiEhQxMlFhgf/EABcBAAMBAAAAAAAAAAAAAAAAAAABAwT/xAAYEQADAQEAAAAAAAAAAAAAAAAAAQIRYf/aAAwDAQACEQMRAD8AKl9a92aYsZFY7bpHfjQGUdK/WmiLSusOjwOw7+xkPQZA7GYKRtfIE87s4wW3Xjd0nkikAPg2ieZnmql8FiGHtK6+QhTf51mn0qfon9XDDAof/9k=",
  },
];
